### PR TITLE
Revert "LED" to Pin 25

### PR DESCRIPTION
**Pull request by tobybroberts**

### CODE REVIEW

**Comment by kilograham** [comment]
out of curiosity why was this reverted?

**Comment by lurch** [comment]
Because it doesn't work on Pico W, so we thought if we leave it as `25` it makes it more obvious that it only works on Pico; whereas `"LED"` might imply that it works on both.

**Comment by kilograham** [comment]
umm.. Pico W was the entire reason for adding "LED" to MP for RP2040 in the first place, when did it get broken? seems like someone ought to fix it.

**Comment by dpgeorge** [comment]
The `"LED"` string does work on Pico W, but the example here is about PWM, and PWM doesn't work on that LED.

```
>>> machine.PWM(machine.Pin("LED"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: expecting a regular GPIO Pin
```

**Comment by lurch** [comment]
Yes, sorry I should have clarified that the "LED" string works for regular-GPIO on both Pico and Pico W, but doesn't work with PIO or PWM on Pico W. See also #60

**Pull request merged**
