### PR TITLE
Added Buzzer Program for user reference

### PR DESCRIPTION
**Pull request by atyadav**
Would like to get this example added to your master branch. Hope ths would help users to experiment with buzzer.

### CODE REVIEW

**Comment by aallan** [comment]
Hey. As a stand alone code example this probably doesn't qualify for addition as it doesn't add any new content to the PWM examples that exist in [the Python book](https://datasheets.raspberrypi.org/pico/sdk/pico_python_sdk.pdf) already. 

However if you take a look at something like the [NeoPixel Ring](https://github.com/raspberrypi/pico-micropython-examples/tree/master/pio/neopixel_ring) example you'll see one of the full featured "app note" style code examples which include a wiring diagram (done using Fritzing, the Pico Fritzing part is available from the [Getting Started page](https://www.raspberrypi.org/documentation/pico/getting-started/). 

If you want to go ahead and add an asciidoc write up along those lines that might then qualify it for inclusion in the examples. Thanks!

**Comment by atyadav** [comment]
> Hey. As a stand alone code example this probably doesn't qualify for addition as it doesn't add any new content to the PWM examples that exist in [the Python book](https://datasheets.raspberrypi.org/pico/sdk/pico_python_sdk.pdf) already.
> 
> However if you take a look at something like the [NeoPixel Ring](https://github.com/raspberrypi/pico-micropython-examples/tree/master/pio/neopixel_ring) example you'll see one of the full featured "app note" style code examples which include a wiring diagram (done using Fritzing, the Pico Fritzing part is available from the [Getting Started page](https://www.raspberrypi.org/documentation/pico/getting-started/).
> 
> If you want to go ahead and add an asciidoc write up along those lines that might then qualify it for inclusion in the examples. Thanks!

Sure shall have a look and try to modify accordingly.

**Comment by atyadav** [comment]
Shall Update circuit diagram and other details as suggested.

**Comment by aallan** [comment]
Thanks, see also the top level [README](https://github.com/raspberrypi/pico-micropython-examples/blob/master/README.md) for licensing conditions.

**Pull request closed without merging**
