### PR TITLE
pio/pio_blink.py: fix missing rp2 import.

### PR DESCRIPTION
**Pull request by hoihu**
Example did run when copy&pasting in REPL, but did not when importing the file

### CODE REVIEW

**Comment by aallan** [comment]
Just tested in Thonny with the launch version of MicroPython, pico_micropython_20210121.uf2. It works as described, and the LED blinks for 3 seconds. There is an PIO issue with the latest release of MicroPython, see micropython/micropython#6837 for details. Try installing the [launch version](https://www.raspberrypi.org/documentation/pico/getting-started/static/5d8e777377e8dbe23cf36360d6efc727/pico_micropython_20210121.uf2) and see if that helps?

**Comment by hoihu** [comment]
Thanks for testing, I'm aware of the issue you've linked, but this is not related to it. I'm using a local build that doesn't have this problem.

The problem really is that `rp2` is not imported in the namespace of the file. It will work then copy&pasting via REPL / raw REPL (and perhaps Thonny is doing that?)

So to recreate the issue: copy over the pio_blink.py file, then issue the following on the REPL:
```
Type "help()" for more information.
>>> import pio_blink
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pio_blink.py", line 7, in <module>
NameError: name 'rp2' isn't defined
>>> 
```

**Comment by lurch** [comment]
@aallan I agree that this fix is "correct". All our micropython PIO examples are either using `import rp2` at the top, and then referencing e.g. `rp2.asm_pio`, `rp2.PIO.OUT_LOW` and `rp2.StateMachine` in the code; or they're doing `from rp2 import PIO, StateMachine, asm_pio` at the top, and then referencing `asm_pio`, `PIO.OUT_LOW` and `StateMachine` in the code.

This PR makes `pio_blink.py` consistent with all our other examples. Also, it seems like https://github.com/raspberrypi/pico-micropython-examples/blob/master/pio/pio_spi.py is also missing an `import rp2` line.

**Comment by aallan** [comment]
> This PR makes `pio_blink.py` consistent with all our other examples. Also, it seems like https://github.com/raspberrypi/pico-micropython-examples/blob/master/pio/pio_spi.py is also missing an import rp2 line.

Okay thanks.

**Pull request merged**
