### PR TITLE
webserver.py: Change `Pin 15` to `Pin LED`

### PR DESCRIPTION
**Pull request by pkoscik**
This example does not work correctly RPI Pico W. Accessing the `light/on` and `light/off` endpoints does not toggle the LED state.

This patch fixes the issue.

### CODE REVIEW

**Comment by lurch** [comment]
See section 3.9.2 of https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf - I believe this PR is redundant?

**Comment by bwenrich** [comment]
Confirming that the existing sample code does not toggle the LED in my environment (Pico W with MicroPython v1.22.1). Manually managing a different pin number for Pico and Pico W is not complex, but is annoying. ex: https://forums.raspberrypi.com/viewtopic.php?t=336836 In recent versions of MicroPython this should no longer be necessary.

If I am reading correctly, [MicroPython 1.20](https://github.com/micropython/micropython/releases/tag/v1.20.0) introduces support for the `Pin("LED", Pin.OUT)` syntax via the "named pins" feature, which is also the first time they are providing a Pico W-specific build. Considering that this example is most relevant for the Pico W's network hardware, maintaining compatibility with older releases for the Pico may not be too concerning.

My opinion is that this PR would be helpful for two reasons:
- Improves the user experience. New users who try these samples on the current version of MicroPython will get a functioning example
- Consistency with other examples in this repo. This syntax is already used in other examples such as the basic blink.py https://github.com/raspberrypi/pico-micropython-examples/blob/2cfb06c8f7350ae012631374195b434548aff52a/blink/blink.py#L3

**Comment by dpgeorge** [comment]
> See section 3.9.2 of https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf

This example in the datasheet there suggests that an external LED is connected to GPIO 15, and so the code is written assuming such a wiring.  I guess that's done to teach how to wire up parts, rather than relying on the built-in LED.

> If I am reading correctly, [MicroPython 1.20](https://github.com/micropython/micropython/releases/tag/v1.20.0) introduces support for the `Pin("LED", Pin.OUT)` syntax via the "named pins" feature,

Yes that is correct.  It's now possible to access the built-in LED on both the Pico and Pico W using `Pin("LED")`.  So the example code could be changed to use the built-in LED, but then any external LED that's wired to GPIO 15 wouldn't work.

**Review by aallan — APPROVED** [review]

**Comment by aallan** [comment]
Reverted #71. See the description of this example in Section 3.9.2 of https://datasheets.raspberrypi.com/picow/connecting-to-the-internet-with-pico-w.pdf. This was *never supposed to work with the onboard LED* so shouldn't be using the LED pragma.

**Pull request merged**
